// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: client/user.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_client_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_client_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SubscribeUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUsersRequest) Reset() {
	*x = SubscribeUsersRequest{}
	mi := &file_client_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUsersRequest) ProtoMessage() {}

func (x *SubscribeUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUsersRequest.ProtoReflect.Descriptor instead.
func (*SubscribeUsersRequest) Descriptor() ([]byte, []int) {
	return file_client_user_proto_rawDescGZIP(), []int{1}
}

var File_client_user_proto protoreflect.FileDescriptor

const file_client_user_proto_rawDesc = "" +
	"\n" +
	"\x11client/user.proto\x12\x0eexample.client\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x17\n" +
	"\x15SubscribeUsersRequest2^\n" +
	"\vUserService\x12O\n" +
	"\x0eSubscribeUsers\x12%.example.client.SubscribeUsersRequest\x1a\x14.example.client.User0\x01B\x10Z\x0eexample/clientb\x06proto3"

var (
	file_client_user_proto_rawDescOnce sync.Once
	file_client_user_proto_rawDescData []byte
)

func file_client_user_proto_rawDescGZIP() []byte {
	file_client_user_proto_rawDescOnce.Do(func() {
		file_client_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_user_proto_rawDesc), len(file_client_user_proto_rawDesc)))
	})
	return file_client_user_proto_rawDescData
}

var file_client_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: example.client.User
	(*SubscribeUsersRequest)(nil), // 1: example.client.SubscribeUsersRequest
}
var file_client_user_proto_depIdxs = []int32{
	1, // 0: example.client.UserService.SubscribeUsers:input_type -> example.client.SubscribeUsersRequest
	0, // 1: example.client.UserService.SubscribeUsers:output_type -> example.client.User
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_user_proto_init() }
func file_client_user_proto_init() {
	if File_client_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_user_proto_rawDesc), len(file_client_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_user_proto_goTypes,
		DependencyIndexes: file_client_user_proto_depIdxs,
		MessageInfos:      file_client_user_proto_msgTypes,
	}.Build()
	File_client_user_proto = out.File
	file_client_user_proto_goTypes = nil
	file_client_user_proto_depIdxs = nil
}
