// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"database/sql"
	"example/bootstrap"
	"example/helper"
	"example/input/abstract"
	"example/input/client"
	"example/input/consumer"
	"example/input/grpc"
	"example/input/http"
	"example/input/port"
	"example/output/mysql"
	"example/usecase"
	grpc2 "google.golang.org/grpc"
)

// Injectors from wire.go:

func InitContainer(sMysqlDSN MysqlDSN, sAmqpDSN AmqpDSN, sGrpcAddr GrpcAddr) (*Container, error) {
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractHandler := abstract.NewAbstractHandler(aesHelper)
	db, err := provideMysqlDB(sMysqlDSN)
	if err != nil {
		return nil, err
	}
	userRepository := mysql.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userConsumer, err := provideUserConsumer(sAmqpDSN, userUsecase, abstractHandler)
	if err != nil {
		return nil, err
	}
	clientConn, err := provideGrpcConn(sGrpcAddr)
	if err != nil {
		return nil, err
	}
	userHandler := client.NewUserHandler(clientConn, userUsecase, abstractHandler)
	grpcUserHandler := grpc.NewUserHandler(userUsecase, abstractHandler)
	handlerUserHandler := handler.NewUserHandler(userUsecase, abstractHandler)
	container := &Container{
		AbstractHelper:      abstractHelper,
		AesHelper:           aesHelper,
		AbstractHandler:     abstractHandler,
		ConsumerUserHandler: userConsumer,
		ClientUserHandler:   userHandler,
		GrpcUserHandler:     grpcUserHandler,
		HttpUserHandler:     handlerUserHandler,
	}
	return container, nil
}

// wire.go:

type MysqlDSN string

type AmqpDSN string

type GrpcAddr string

// provideMysqlDB / provideGrpcConn / provideUserConsumer 只是把型別化的 DSN
// 轉成 bootstrap 原本要的 string，本身邏輯完全沒動。
func provideMysqlDB(sDSN MysqlDSN) (*sql.DB, error) {
	return bootstrap.NewMysql(string(sDSN))
}

func provideGrpcConn(sAddr GrpcAddr) (*grpc2.ClientConn, error) {
	return bootstrap.NewClient(string(sAddr))
}

func provideUserConsumer(sDSN AmqpDSN, oUsecase port.UserUsecase, oAbstractHandler *abstract.AbstractHandler) (*consumer.UserConsumer, error) {
	return consumer.NewUserConsumer(string(sDSN), oUsecase, oAbstractHandler)
}

type Container struct {
	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*abstract.AbstractHandler

	// Input Adapter：四種輸入來源共用同一個 UserUsecase
	ConsumerUserHandler *consumer.UserConsumer // MQ 消費者
	ClientUserHandler   *client.UserHandler    // gRPC client stream 訂閱
	GrpcUserHandler     *grpc.UserHandler      // gRPC server
	HttpUserHandler     *handler.UserHandler   // HTTP handler
}
