// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: facade/table/scanner.proto

package pb_facade_table

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneRequest) Reset() {
	*x = OneRequest{}
	mi := &file_facade_table_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneRequest) ProtoMessage() {}

func (x *OneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_table_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneRequest.ProtoReflect.Descriptor instead.
func (*OneRequest) Descriptor() ([]byte, []int) {
	return file_facade_table_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *OneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneResponse) Reset() {
	*x = OneResponse{}
	mi := &file_facade_table_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneResponse) ProtoMessage() {}

func (x *OneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_table_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneResponse.ProtoReflect.Descriptor instead.
func (*OneResponse) Descriptor() ([]byte, []int) {
	return file_facade_table_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *OneResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_facade_table_scanner_proto protoreflect.FileDescriptor

const file_facade_table_scanner_proto_rawDesc = "" +
	"\n" +
	"\x1afacade/table/scanner.proto\x12\x0fpb.facade.table\" \n" +
	"\n" +
	"OneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\vOneResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2O\n" +
	"\aScanner\x12D\n" +
	"\aPostOne\x12\x1b.pb.facade.table.OneRequest\x1a\x1c.pb.facade.table.OneResponseB\x13Z\x11./pb_facade_tableb\x06proto3"

var (
	file_facade_table_scanner_proto_rawDescOnce sync.Once
	file_facade_table_scanner_proto_rawDescData []byte
)

func file_facade_table_scanner_proto_rawDescGZIP() []byte {
	file_facade_table_scanner_proto_rawDescOnce.Do(func() {
		file_facade_table_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facade_table_scanner_proto_rawDesc), len(file_facade_table_scanner_proto_rawDesc)))
	})
	return file_facade_table_scanner_proto_rawDescData
}

var file_facade_table_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_facade_table_scanner_proto_goTypes = []any{
	(*OneRequest)(nil),  // 0: pb.facade.table.OneRequest
	(*OneResponse)(nil), // 1: pb.facade.table.OneResponse
}
var file_facade_table_scanner_proto_depIdxs = []int32{
	0, // 0: pb.facade.table.Scanner.PostOne:input_type -> pb.facade.table.OneRequest
	1, // 1: pb.facade.table.Scanner.PostOne:output_type -> pb.facade.table.OneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_facade_table_scanner_proto_init() }
func file_facade_table_scanner_proto_init() {
	if File_facade_table_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facade_table_scanner_proto_rawDesc), len(file_facade_table_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facade_table_scanner_proto_goTypes,
		DependencyIndexes: file_facade_table_scanner_proto_depIdxs,
		MessageInfos:      file_facade_table_scanner_proto_msgTypes,
	}.Build()
	File_facade_table_scanner_proto = out.File
	file_facade_table_scanner_proto_goTypes = nil
	file_facade_table_scanner_proto_depIdxs = nil
}
