// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitContainer() *Container {
	movieModel := NewMovieModel()
	movieLogic := NewMovieLogic(movieModel)
	movieController := NewMovieController(movieModel, movieLogic)
	container := &Container{
		MovieModel:      movieModel,
		MovieLogic:      movieLogic,
		MovieController: movieController,
	}
	return container
}

// wire.go:

// 定義一個 Root Object, 便於取得所有 物件
type Container struct {
	*MovieModel
	*MovieLogic
	*MovieController
}
