default:
  directory: './runtime/logger/default'
  max_size: 10000
  max_backups: 7
  max_age: 30
  compress: true
middleware:
  directory: './runtime/logger/middleware'
  max_size: 10000
  max_backups: 7
  max_age: 30
  compress: true
controller:
  directory: './runtime/logger/controller'
  max_size: 10000
  max_backups: 7
  max_age: 30
  compress: true
sdk:
  directory: './runtime/logger/sdk'
  max_size: 10000
  max_backups: 7
  max_age: 30
  compress: true
service:
  directory: './runtime/logger/service'
  max_size: 10000
  max_backups: 7
  max_age: 30
  compress: true