// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pb/heartbeater.proto

package pb_heartbeater

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // 客户端唯一識別碼
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 發送時間戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_pb_heartbeater_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_heartbeater_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_pb_heartbeater_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                            // 狀態，例如 "OK"
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 伺服器接收時間戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_pb_heartbeater_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_heartbeater_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_pb_heartbeater_proto_rawDescGZIP(), []int{1}
}

func (x *PongResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PongResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_pb_heartbeater_proto protoreflect.FileDescriptor

const file_pb_heartbeater_proto_rawDesc = "" +
	"\n" +
	"\x14pb/heartbeater.proto\x12\x0epb.heartbeater\"H\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"G\n" +
	"\fPongResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime2P\n" +
	"\vHeartbeater\x12A\n" +
	"\x04Ping\x12\x1b.pb.heartbeater.PingRequest\x1a\x1c.pb.heartbeater.PongResponseB\x12Z\x10./pb_heartbeaterb\x06proto3"

var (
	file_pb_heartbeater_proto_rawDescOnce sync.Once
	file_pb_heartbeater_proto_rawDescData []byte
)

func file_pb_heartbeater_proto_rawDescGZIP() []byte {
	file_pb_heartbeater_proto_rawDescOnce.Do(func() {
		file_pb_heartbeater_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_heartbeater_proto_rawDesc), len(file_pb_heartbeater_proto_rawDesc)))
	})
	return file_pb_heartbeater_proto_rawDescData
}

var file_pb_heartbeater_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_heartbeater_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: pb.heartbeater.PingRequest
	(*PongResponse)(nil), // 1: pb.heartbeater.PongResponse
}
var file_pb_heartbeater_proto_depIdxs = []int32{
	0, // 0: pb.heartbeater.Heartbeater.Ping:input_type -> pb.heartbeater.PingRequest
	1, // 1: pb.heartbeater.Heartbeater.Ping:output_type -> pb.heartbeater.PongResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_heartbeater_proto_init() }
func file_pb_heartbeater_proto_init() {
	if File_pb_heartbeater_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_heartbeater_proto_rawDesc), len(file_pb_heartbeater_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_heartbeater_proto_goTypes,
		DependencyIndexes: file_pb_heartbeater_proto_depIdxs,
		MessageInfos:      file_pb_heartbeater_proto_msgTypes,
	}.Build()
	File_pb_heartbeater_proto = out.File
	file_pb_heartbeater_proto_goTypes = nil
	file_pb_heartbeater_proto_depIdxs = nil
}
