// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: pb/heartbeater.proto

package pb_heartbeater

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Heartbeater_Ping_FullMethodName = "/pb.heartbeater.Heartbeater/Ping"
)

// HeartbeaterClient is the client API for Heartbeater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 移除 Service 後綴，直接命名為 Heartbeater
type HeartbeaterClient interface {
	// 一問一答型 (Unary RPC) 的心跳探測
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type heartbeaterClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartbeaterClient(cc grpc.ClientConnInterface) HeartbeaterClient {
	return &heartbeaterClient{cc}
}

func (c *heartbeaterClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, Heartbeater_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartbeaterServer is the server API for Heartbeater service.
// All implementations must embed UnimplementedHeartbeaterServer
// for forward compatibility.
//
// 移除 Service 後綴，直接命名為 Heartbeater
type HeartbeaterServer interface {
	// 一問一答型 (Unary RPC) 的心跳探測
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedHeartbeaterServer()
}

// UnimplementedHeartbeaterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeartbeaterServer struct{}

func (UnimplementedHeartbeaterServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedHeartbeaterServer) mustEmbedUnimplementedHeartbeaterServer() {}
func (UnimplementedHeartbeaterServer) testEmbeddedByValue()                     {}

// UnsafeHeartbeaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartbeaterServer will
// result in compilation errors.
type UnsafeHeartbeaterServer interface {
	mustEmbedUnimplementedHeartbeaterServer()
}

func RegisterHeartbeaterServer(s grpc.ServiceRegistrar, srv HeartbeaterServer) {
	// If the following call panics, it indicates UnimplementedHeartbeaterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Heartbeater_ServiceDesc, srv)
}

func _Heartbeater_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartbeaterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Heartbeater_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartbeaterServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Heartbeater_ServiceDesc is the grpc.ServiceDesc for Heartbeater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Heartbeater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.heartbeater.Heartbeater",
	HandlerType: (*HeartbeaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Heartbeater_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/heartbeater.proto",
}
